# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f15d6b3e0daed602f01818c0fee6957cb12a57b20611901d175e7af785fb2d624517a79ef65eac1f6f1665e4d6d2049e4020b872caee921d7178cde019cf70

test:
  secret_key_base: b3eeb6eeed6ff4f10e0c9581ae2108b1de65383b5561b840335651b8f996635363678d1925506f9103c483795bcd7172f4069880dd2b485bb38b8c0c8df03598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
